export const Types = {
    INITIALIZE_CART: "INITIALIZE_CART",
    UPDATE_CART: "UPDATE_CART",
    SAVE_CART: "SAVE_CART",
    CLEAR_CART: "CLEAR_CART",
    SET_PROGRESS: "SET_PROGRESS",
    SET_FEED: "SET_FEED",
    SET_PERSON: "SET_PERSON"
}